### ISSUE TITLE
audioop is deprecated since python version 3.11

### ISSUE THREAD

**Issue by KolodyazhnyyI** [obaskly/AiDetectionBypass#1]
this program doesnt run anymore on new python
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pydub\utils.py", line 14, in <module>
    import audioop
ModuleNotFoundError: No module named 'audioop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\AiDetectionBypass-main\main.py", line 7, in <module>
    from RecaptchaSolver import RecaptchaSolver
  File "D:\Downloads\AiDetectionBypass-main\RecaptchaSolver.py", line 10, in <module>
    from pydub import AudioSegment
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pydub\__init__.py", line 1, in <module>
    from .audio_segment import AudioSegment
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pydub\audio_segment.py", line 11, in <module>
    from .utils import mediainfo_json, fsdecode
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\pydub\utils.py", line 16, in <module>
    import pyaudioop as audioop
ModuleNotFoundError: No module named 'pyaudioop'

D:\Downloads\AiDetectionBypass-main>pip install audioop
ERROR: Could not find a version that satisfies the requirement audioop (from versions: none)
ERROR: No matching distribution found for audioop

D:\Downloads\AiDetectionBypass-main>pip3 install audioop
ERROR: Could not find a version that satisfies the requirement audioop (from versions: none)
ERROR: No matching distribution found for audioop

D:\Downloads\AiDetectionBypass-main>python --version
Python 3.13.0

**Comment by obaskly** [comment]
Downgrade to version 3.10.x
